task_name: 'long_term_forecast'
is_training: 1
model: 'Autoformer'

# Data settings
data: 'ETTh1'
root_path: './data/ETT/'
data_path: 'ETTh1.csv'
features: 'M'  # M: multivariate predict multivariate, S: univariate, MS: multivariate predict univariate
target: 'OT'
freq: 'h'
checkpoints: './checkpoints/'

# Sequence settings
seq_len: 96
label_len: 48
pred_len: 96
seasonal_patterns: null

# Model architecture
enc_in: 7
dec_in: 7
c_out: 7
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 2048
moving_avg: 25
factor: 1
distil: true
dropout: 0.1
embed: 'timeF'
activation: 'gelu'
output_attention: false

# Training settings
num_workers: 10
itr: 1
train_epochs: 10
batch_size: 32
patience: 3
learning_rate: 0.0001
des: 'forecasting_experiment'
loss: 'MSE'
lradj: 'type1'
use_amp: false

# Hardware settings
use_gpu: true
gpu: 0
gpu_type: 'cuda'
use_multi_gpu: false
devices: '0,1,2,3'
seed: 2021

# Misc settings
use_dtw: false
use_tqdm: true